package com.example.restaurantmenu

import com.example.restaurantmenu.enums.Category
import com.example.restaurantmenu.models.Dish

val dishes = listOf<Dish>(
  Dish(
    R.string.sopa_cebola,
    R.string.sopa_cebola_descricao,
    12.0,
    R.drawable.sopa_cebola,
    Category.STARTER,
    8.0
  ),
  Dish(
    R.string.tournedos,
    R.string.tournedos_descricao,
    80.0,
    R.drawable.tournedos,
    Category.MAIN,
    35.0
  ),
  Dish(
    R.string.petit_gateau,
    R.string.petit_gateau_descricao,
    15.0,
    R.drawable.petit_gateau,
    Category.DESSERT,
    10.0
  ),
  Dish(
    R.string.vinho_tinto,
    R.string.vinho_tinto_descricao,
    25.0,
    R.drawable.vinho_tinto,
    Category.DRINK,
    0.0
  ),
  Dish(
    R.string.bruschetta,
    R.string.bruschetta_descricao,
    10.0,
    R.drawable.bruschetta,
    Category.STARTER,
    5.0
  ),
  Dish(
    R.string.pasta_carbonara,
    R.string.pasta_carbonara_descricao,
    45.0,
    R.drawable.pasta_carbonara,
    Category.MAIN,
    25.0
  ),
  Dish(
    R.string.tiramisu,
    R.string.tiramisu_descricao,
    18.0,
    R.drawable.tiramisu,
    Category.DESSERT,
    12.0
  ),
  Dish(
    R.string.cerveja,
    R.string.cerveja_descricao,
    4.0,
    R.drawable.cerveja,
    Category.DRINK,
    0.0
  )
)